[1/10] cd /media/trngzng/Windows/Data/Projects/TFT-DIGITAL-CLOCK-ESP32/Software/build && /home/trngzng/.espressif/python_env/idf5.1_py3.10_env/bin/python /home/trngzng/esp/esp-idf/components/spiffs/spiffsgen.py 0xf0000 /media/trngzng/Windows/Data/Projects/TFT-DIGITAL-CLOCK-ESP32/Software/font /media/trngzng/Windows/Data/Projects/TFT-DIGITAL-CLOCK-ESP32/Software/build/storage.bin --page-size=256 --obj-name-len=32 --meta-len=4 --use-magic --use-magic-len
FAILED: CMakeFiles/spiffs_storage_bin /media/trngzng/Windows/Data/Projects/TFT-DIGITAL-CLOCK-ESP32/Software/build/CMakeFiles/spiffs_storage_bin 
cd /media/trngzng/Windows/Data/Projects/TFT-DIGITAL-CLOCK-ESP32/Software/build && /home/trngzng/.espressif/python_env/idf5.1_py3.10_env/bin/python /home/trngzng/esp/esp-idf/components/spiffs/spiffsgen.py 0xf0000 /media/trngzng/Windows/Data/Projects/TFT-DIGITAL-CLOCK-ESP32/Software/font /media/trngzng/Windows/Data/Projects/TFT-DIGITAL-CLOCK-ESP32/Software/build/storage.bin --page-size=256 --obj-name-len=32 --meta-len=4 --use-magic --use-magic-len
Traceback (most recent call last):
  File "/home/trngzng/esp/esp-idf/components/spiffs/spiffsgen.py", line 434, in create_file
    block.update_obj(contents_chunk)
  File "/home/trngzng/esp/esp-idf/components/spiffs/spiffsgen.py", line 349, in update_obj
    raise SpiffsFullError()
__main__.SpiffsFullError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/trngzng/esp/esp-idf/components/spiffs/spiffsgen.py", line 438, in create_file
    raise SpiffsFullError
__main__.SpiffsFullError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/trngzng/esp/esp-idf/components/spiffs/spiffsgen.py", line 593, in <module>
    main()
  File "/home/trngzng/esp/esp-idf/components/spiffs/spiffsgen.py", line 585, in main
    spiffs.create_file('/' + os.path.relpath(full_path, args.base_dir).replace('\\', '/'), full_path)
  File "/home/trngzng/esp/esp-idf/components/spiffs/spiffsgen.py", line 449, in create_file
    block = self._create_block()
  File "/home/trngzng/esp/esp-idf/components/spiffs/spiffsgen.py", line 398, in _create_block
    raise SpiffsFullError('the image size has been exceeded')
__main__.SpiffsFullError: the image size has been exceeded
[2/10] Performing build step for 'bootloader'
[1/1] cd /media/trngzng/Windows/Data/Projects/TFT-DIGITAL-CLOCK-ESP32/Software/build/bootloader/esp-idf/esptool_py && /home/trngzng/.espressif/python_env/idf5.1_py3.10_env/bin/python /home/trngzng/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 /media/trngzng/Windows/Data/Projects/TFT-DIGITAL-CLOCK-ESP32/Software/build/bootloader/bootloader.bin
Bootloader binary size 0x6730 bytes. 0x8d0 bytes (8%) free.
[3/8] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj
ninja: build stopped: subcommand failed.
